server:
  port: 9099
  error:
    whitelabel:
      enabled: false   # 关闭默认错误页，交给全局异常处理器

spring:
  application:
    name: response-exception-log
  mvc:
    throw-exception-if-no-handler-found: true   # 404 交给全局异常处理器
  web:
    resources:
      add-mappings: false

logging:
  config: classpath:logback-spring.xml
